# GoReleaser v2 configuration for matrix builds
version: 2

project_name: lawrence

before:
  hooks:
    - go mod tidy

builds:
  - id: lawrence
    main: .
    binary: lawrence
    env:
      - CGO_ENABLED=1
    # Target platforms - will be overridden by matrix builds
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/getlawrence/cli/cmd.Version={{.Version}}
      - -X github.com/getlawrence/cli/cmd.GitCommit={{.Commit}}
      - -X github.com/getlawrence/cli/cmd.BuildDate={{ time "2006-01-02T15:04:05Z07:00" }}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  draft: false
  make_latest: false

changelog:
  use: git
  sort: asc

# Note: This configuration is now used primarily for local testing
# The actual releases are built using the GitHub Actions matrix workflow
# which builds natively on each platform for better compatibility