project_name: lawrence

before:
  hooks:
    - go mod tidy

builds:
  - id: lawrence
    main: .
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/getlawrence/cli/cmd.Version={{.Version}}
      - -X github.com/getlawrence/cli/cmd.GitCommit={{.Commit}}
      - -X github.com/getlawrence/cli/cmd.BuildDate={{ time "2006-01-02T15:04:05Z07:00" }}

archives:
  - id: default
    builds: [lawrence]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  draft: false
  make_latest: false

changelog:
  use: git
  sort: asc

brews:
  - name: lawrence
    ids: [lawrence]
    tap:
      owner: getlawrence
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: noreply@getlawrence.dev
    homepage: https://github.com/getlawrence/cli
    description: CLI tool to analyze codebases and instrument them with OpenTelemetry
    license: MIT
    test: |
      assert_match "OpenTelemetry codebase analyzer", shell_output("#{bin}/lawrence --help")
    commit_msg_template: "chore(brew): update {{ .ProjectName }} to {{ .Tag }}"
