version: '3.8'

services:
  lawrence-e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      - ./e2e-results:/test/results
    environment:
      - CI=true
      - TEST_TIMEOUT=300
    networks:
      - lawrence-test
    command: ["/test/e2e/run-tests.sh"]

  # Additional service for testing in different environments
  lawrence-e2e-alpine:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      target: alpine-test
    volumes:
      - ./e2e-results:/test/results
    environment:
      - CI=true
      - DISTRO=alpine
    networks:
      - lawrence-test
    profiles:
      - multi-distro

  # Service for running specific test suites
  lawrence-instrumentation-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      - ./e2e-results:/test/results
    environment:
      - CI=true
    networks:
      - lawrence-test
    command: ["/test/e2e/test-instrumentation.sh"]
    profiles:
      - instrumentation

networks:
  lawrence-test:
    driver: bridge

volumes:
  e2e-results:
