extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  file:
    path: /data/traces.jsonl
    rotation:
      max_megabytes: 5
      max_days: 1
      max_backups: 1
  logging:
    loglevel: info

processors:
  batch: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging]

