name: Create Homebrew Tap

on:
  workflow_dispatch:
    inputs:
      tap_name:
        description: 'Homebrew tap name (e.g., getlawrence/tap)'
        required: true
        default: 'getlawrence/tap'
      repository_name:
        description: 'Repository name for the tap'
        required: true
        default: 'homebrew-tap'

jobs:
  create-tap:
    name: Create Homebrew Tap Repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create Homebrew tap repository
        run: |
          echo "Creating Homebrew tap repository: ${{ inputs.tap_name }}"
          
          # Create the tap repository using GitHub CLI
          gh repo create ${{ inputs.repository_name }} \
            --public \
            --description "Homebrew tap for Lawrence CLI" \
            --homepage "https://github.com/getlawrence/cli" \
            --template "homebrew/homebrew-tap" \
            --clone

      - name: Copy Homebrew formula
        run: |
          cd ${{ inputs.repository_name }}
          
          # Copy the formula from the main repository
          cp ../homebrew/lawrence.rb Formula/
          
          # Update the formula to use latest release
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest release: $LATEST_RELEASE"
          
          # Update URLs to use latest release
          sed -i "s|url \".*darwin_arm64.tar.gz\"|url \"https://github.com/getlawrence/cli/releases/download/$LATEST_RELEASE/lawrence_$LATEST_RELEASE_darwin_arm64.tar.gz\"|" Formula/lawrence.rb
          sed -i "s|url \".*darwin_amd64.tar.gz\"|url \"https://github.com/getlawrence/cli/releases/download/$LATEST_RELEASE/lawrence_$LATEST_RELEASE_darwin_amd64.tar.gz\"|" Formula/lawrence.rb
          sed -i "s|url \".*linux_amd64.tar.gz\"|url \"https://github.com/getlawrence/cli/releases/download/$LATEST_RELEASE/lawrence_$LATEST_RELEASE_linux_amd64.tar.gz\"|" Formula/lawrence.rb
          
          # Get SHA256 hashes from latest release
          gh release download $LATEST_RELEASE --dir temp
          cd temp
          find . -name "*.tar.gz" -exec shasum -a 256 {} \; > checksums.txt
          
          LINUX_SHA=$(grep "linux_amd64.tar.gz" checksums.txt | awk '{print $1}')
          DARWIN_AMD64_SHA=$(grep "darwin_amd64.tar.gz" checksums.txt | awk '{print $1}')
          DARWIN_ARM64_SHA=$(grep "darwin_arm64.tar.gz" checksums.txt | awk '{print $1}')
          
          cd ..
          
          # Update SHA256 hashes
          sed -i "/darwin_arm64.tar.gz/,/sha256/s|sha256 \".*\"|sha256 \"$DARWIN_ARM64_SHA\"|" Formula/lawrence.rb
          sed -i "/darwin_amd64.tar.gz/,/sha256/s|sha256 \".*\"|sha256 \"$DARWIN_AMD64_SHA\"|" Formula/lawrence.rb
          sed -i "/linux_amd64.tar.gz/,/sha256/s|sha256 \".*\"|sha256 \"$LINUX_SHA\"|" Formula/lawrence.rb
          
          # Clean up
          rm -rf temp

      - name: Commit and push to tap repository
        run: |
          cd ${{ inputs.repository_name }}
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add .
          git commit -m "Add Lawrence CLI formula

- Add Lawrence CLI Homebrew formula
- Support for macOS ARM64, AMD64, and Linux AMD64
- Formula automatically updated from main repository"
          
          git push origin main

      - name: Show tap information
        run: |
          echo "✅ Homebrew tap created successfully!"
          echo "Tap: ${{ inputs.tap_name }}"
          echo "Repository: https://github.com/getlawrence/${{ inputs.repository_name }}"
          echo ""
          echo "Users can now install Lawrence CLI using:"
          echo "brew tap ${{ inputs.tap_name }}"
          echo "brew install ${{ inputs.tap_name }}/lawrence"
