name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test ./...

    - name: Build binaries
      run: |
        # Set version info
        VERSION=${GITHUB_REF#refs/tags/}
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        GIT_COMMIT=${GITHUB_SHA}
        LDFLAGS="-s -w -X github.com/getlawrence/cli/cmd.Version=${VERSION} -X github.com/getlawrence/cli/cmd.GitCommit=${GIT_COMMIT} -X github.com/getlawrence/cli/cmd.BuildDate=${BUILD_DATE}"
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o lawrence-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o lawrence-linux-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o lawrence-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o lawrence-windows-arm64.exe .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o lawrence-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o lawrence-darwin-arm64 .

    - name: Create checksums
      run: |
        sha256sum lawrence-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          lawrence-*
          checksums.txt
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
