name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  GORELEASER_VERSION: v2.11.2

jobs:
  prev-tag:
    outputs:
      PREVIOUS_RELEASE_TAG: ${{ steps.prev-tag.outputs.PREVIOUS_RELEASE_TAG }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set goreleaser last tag reference
        id: prev-tag
        run: |
          prev_tag=$(git tag | sort -r --version-sort | head -n 2 | tail -n 1)
          echo "PREVIOUS_RELEASE_TAG=$prev_tag" >> "$GITHUB_OUTPUT"

  build-linux:
    name: Build Linux AMD64
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          install-only: true

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v1
          CGO_ENABLED: 1
        run: |
          go build -ldflags="-s -w -X github.com/getlawrence/cli/cmd.Version=${{ github.ref_name }} -X github.com/getlawrence/cli/cmd.GitCommit=${{ github.sha }} -X github.com/getlawrence/cli/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o lawrence-linux-amd64 .

      - name: Create archive
        run: |
          mkdir -p dist
          tar -czf dist/lawrence_${{ github.ref_name }}_linux_amd64.tar.gz lawrence-linux-amd64 LICENSE README.md

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux-amd64
          path: dist/
          if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - prev-tag
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
          check-latest: true

      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: dist/
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R dist/

      - name: Create checksums
        run: |
          cd dist
          find . -name "*.tar.gz" -exec shasum -a 256 {} \; > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Lawrence CLI ${{ github.ref_name }}
          body: |
            ## Lawrence CLI ${{ github.ref_name }}
            
            ### Downloads
            
            **Linux AMD64:**
            - [lawrence_${{ github.ref_name }}_linux_amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lawrence_${{ github.ref_name }}_linux_amd64.tar.gz)
            
            ### Checksums
            
            ```
            $(cat dist/checksums.txt)
            ```
            
            ### Changes since ${{ needs.prev-tag.outputs.PREVIOUS_RELEASE_TAG }}
            
            $(git log --oneline ${{ needs.prev-tag.outputs.PREVIOUS_RELEASE_TAG }}..HEAD)
          files: dist/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
