name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-linux:
    name: Release Linux AMD64
    uses: ./.github/workflows/base-release.yaml
    with:
      goos: '["linux"]'
      goarch: '["amd64"]'
      runner_os: ubuntu-latest
    secrets: inherit
    permissions: write-all

  release-windows:
    name: Release Windows AMD64
    uses: ./.github/workflows/base-release.yaml
    with:
      goos: '["windows"]'
      goarch: '["amd64"]'
      runner_os: windows-latest
    secrets: inherit
    permissions: write-all

  release-macos-amd64:
    name: Release macOS AMD64
    uses: ./.github/workflows/base-release.yaml
    with:
      goos: '["darwin"]'
      goarch: '["amd64"]'
      runner_os: macos-latest
    secrets: inherit
    permissions: write-all

  release-macos-arm64:
    name: Release macOS ARM64
    uses: ./.github/workflows/base-release.yaml
    with:
      goos: '["darwin"]'
      goarch: '["arm64"]'
      runner_os: macos-latest
    secrets: inherit
    permissions: write-all

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - release-linux
      - release-windows
      - release-macos-amd64
      - release-macos-arm64
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
          check-latest: true

      - name: Get previous tag
        id: prev-tag
        run: |
          prev_tag=$(git tag | sort -r --version-sort | head -n 2 | tail -n 1)
          echo "PREVIOUS_RELEASE_TAG=$prev_tag" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: dist/
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R dist/

      - name: Create checksums
        run: |
          cd dist
          find . -name "*.tar.gz" -exec shasum -a 256 {} \; > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Lawrence CLI ${{ github.ref_name }}
          body: |
            ## Lawrence CLI ${{ github.ref_name }}
            
            ### Downloads
            
            **Linux AMD64:**
            - [lawrence_${{ github.ref_name }}_linux_amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lawrence_${{ github.ref_name }}_linux_amd64.tar.gz)
            
            **Windows AMD64:**
            - [lawrence_${{ github.ref_name }}_windows_amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lawrence_${{ github.ref_name }}_windows_amd64.tar.gz)
            
            **macOS AMD64:**
            - [lawrence_${{ github.ref_name }}_darwin_amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lawrence_${{ github.ref_name }}_darwin_amd64.tar.gz)
            
            **macOS ARM64:**
            - [lawrence_${{ github.ref_name }}_darwin_arm64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lawrence_${{ github.ref_name }}_darwin_arm64.tar.gz)
            
            ### Checksums
            
            ```
            $(cat dist/checksums.txt)
            ```
            
            ### Changes since ${{ steps.prev-tag.outputs.PREVIOUS_RELEASE_TAG }}
            
            $(git log --oneline ${{ steps.prev-tag.outputs.PREVIOUS_RELEASE_TAG }}..HEAD)
          files: dist/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
